version: "3.8"

services:
  db-local:
    image: mariadb
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MARIADB_DATABASE: $DB_DATABASE
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./output/local-db:/var/lib/mysql
